import { getPool, query } from './db.js';
import { executeTool } from './tool-execution.js';
import { externalToolRegistry } from './external-tools.js';
import { getSessionUser } from './auth.js';
import { startProgress, updateProgress, finishProgress, registerAgentProgressRoutes } from './agent-progress.js';

const API_BASE='https://generativelanguage.googleapis.com/v1beta/interactions';
const DEFAULT_MODEL=process.env.GEMINI_AGENT_MODEL||'gemini-3.8-flash';
const MAX_GOAL_LENGTH=12000, MAX_TASKS=12, MAX_AGENT_STEPS=16;
const TOOL_NAMES=['research','verify','synthesize','github_repo','github_file','github_issues','aws_read'];
const DEFAULT_PERMISSIONS={web_read:true,file_read:true,code_execution:false,external_write:false,destructive_actions:false};
function apiKey(){return process.env.GEMINI_API_KEY||process.env.GOOGLE_API_KEY||'';}
function clampText(v,max){return String(v||'').slice(0,max);}
function parseJson(t){const c=String(t||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/i,'');try{return JSON.parse(c)}catch{return null}}
const taskSchema={type:'object',additionalProperties:false,properties:{objective:{type:'string'},tasks:{type:'array',minItems:1,maxItems:MAX_TASKS,items:{type:'object',additionalProperties:false,properties:{id:{type:'string'},title:{type:'string'},tool:{type:'string',enum:TOOL_NAMES},input:{type:'string'},depends_on:{type:'array',maxItems:MAX_TASKS,items:{type:'string'}},risk:{type:'string',enum:['low','medium','high']}},required:['id','title','tool','input','depends_on','risk']}}},required:['objective','tasks']};
function heuristicPlan(goal){const l=goal.toLowerCase(),tasks=[];if(/github|repository|repo|pull request|issue|codebase|source code/.test(l)){tasks.push({id:'github_1',title:'Inspect GitHub repository',tool:'github_repo',input:goal,depends_on:[],risk:'low'});if(/file|code|config|bug|error|deployment|deploy/.test(l))tasks.push({id:'github_2',title:'Inspect relevant repository files',tool:'github_file',input:'Inspect the relevant file or directory suggested by github_1.',depends_on:['github_1'],risk:'low'});if(/issue|bug|problem|error/.test(l))tasks.push({id:'github_3',title:'Inspect repository issues',tool:'github_issues',input:'Find relevant issues for the repository.',depends_on:['github_1'],risk:'low');}else if(/aws|cloud|ec2|rds|redis|infrastructure/.test(l))tasks.push({id:'aws_1',title:'Inspect AWS read-only identity',tool:'aws_read',input:'Inspect the configured AWS read-only identity.',depends_on:[],risk:'low'});else if(/research|latest|compare|investigate|analy[sz]e|find|verify|sources|web/.test(l))tasks.push({id:'research_1',title:'Research the objective',tool:'research',input:goal,depends_on:[],risk:'low'});if(tasks.length&&tasks[0].tool!=='research'&&/research|latest|source|verify/.test(l))tasks.push({id:'research_1',title:'Research supporting context',tool:'research',input:goal,depends_on:[],risk:'low'});if(tasks.length&&tasks.some(t=>t.tool==='research'))tasks.push({id:'verify_1',title:'Verify important findings',tool:'verify',input:'Verify factual findings from the available execution evidence.',depends_on:['research_1'],risk:'low'});if(tasks.length)tasks.push({id:'synthesize_1',title:'Synthesize the final answer',tool:'synthesize',input:goal,depends_on:tasks.map(t=>t.id),risk:'low'});else tasks.push({id:'synthesize_1',title:'Analyze the user goal',tool:'synthesize',input:goal,depends_on:[],risk:'low'});return{objective:goal,tasks};}
async function planWithGemini(goal,fetchImpl=fetch){const key=apiKey();if(!key)return heuristicPlan(goal);const body={model:DEFAULT_MODEL,input:`Plan this autonomous task using ONLY these tools: ${TOOL_NAMES.join(', ')}. GitHub and AWS tools are READ-ONLY. Select tools based on the user's actual need, use dependencies when one tool's output informs another, and never invent tools or claim writes occurred. Goal:\n${goal}`,store:false,response_format:{type:'text',mime_type:'application/json',schema:taskSchema}};const r=await fetchImpl(API_BASE,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||`Agent planner failed (${r.status}).`);const p=parseJson(d?.output_text||(d?.steps||[]).flatMap(s=>s?.content||[]).map(x=>x?.text||'').join('\n'));if(!p||!Array.isArray(p.tasks)||!p.tasks.length)throw new Error('Agent planner returned an invalid plan.');p.tasks=p.tasks.slice(0,MAX_TASKS);return p;}
function validatePlan(p){if(!p||!Array.isArray(p.tasks)||p.tasks.length<1||p.tasks.length>MAX_TASKS)throw new Error('Invalid agent plan.');const ids=new Set();for(const t of p.tasks){if(!t?.id||ids.has(t.id))throw new Error('Agent plan contains duplicate or missing task IDs.');if(!TOOL_NAMES.includes(t.tool))throw new Error('Agent plan contains an unsupported tool.');if((t.tool.startsWith('github_')||t.tool==='aws_read')&&t.risk!=='low')throw new Error('External read-only tools must have low risk.');ids.add(t.id)}for(const t of p.tasks)for(const dep of t.depends_on||[])if(!ids.has(dep)||dep===t.id)throw new Error('Agent plan contains an invalid dependency.');return true;}
function topologicalTasks(tasks){const pending=new Map(tasks.map(t=>[t.id,t])),done=new Set(),ordered=[];while(pending.size){let progress=false;for(const[id,t]of pending)if((t.depends_on||[]).every(d=>done.has(d))){ordered.push(t);done.add(id);pending.delete(id);progress=true}if(!progress)throw new Error('Agent plan contains a dependency cycle.')}return ordered;}
async function geminiTool(prompt,options={}){const key=apiKey();if(!key)return{status:'not_executed',reason:'Gemini API is not configured.'};const body={model:DEFAULT_MODEL,input:prompt,store:false};if(options.tools)body.tools=options.tools;const r=await(options.fetchImpl||fetch)(API_BASE,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error?.message||`${options.name||'Agent tool'} failed (${r.status}).`);return{status:'completed',output:d?.output_text||(d?.steps||[]).flatMap(s=>s?.content||[]).map(x=>x?.text||'').filter(Boolean).join('\n'),steps:d?.steps||[]};}
async function runResearch(i,c,f){return geminiTool(`Research this task and cite useful sources.\n\n${clampText(i,MAX_GOAL_LENGTH)}`,{tools:[{type:'google_search'}],fetchImpl:f,name:'Research tool'});}
async function runVerify(i,c,f){return geminiTool(`Verify factual claims using web evidence.\n\nTASK:\n${i}\n\nCONTEXT:\n${clampText(JSON.stringify(c),30000)}`,{tools:[{type:'google_search'}],fetchImpl:f,name:'Verification tool'});}
async function runSynthesize(i,c,f){return geminiTool(`Produce a concise final answer. Use execution evidence, distinguish uncertainty, and never claim an action happened unless evidence shows it.\n\nGOAL:\n${i}\n\nEVIDENCE:\n${clampText(JSON.stringify(c),45000)}`,{fetchImpl:f,name:'Synthesis tool'});}
const TOOL_REGISTRY={research:runResearch,verify:runVerify,synthesize:runSynthesize,...externalToolRegistry()};
export async function runAgent(goal,options={}){const cleanGoal=String(goal||'').trim();if(!cleanGoal)throw new Error('Agent goal is required.');if(cleanGoal.length>MAX_GOAL_LENGTH)throw new Error('Agent goal is too long.');const plan=options.plan||await planWithGemini(cleanGoal,options.fetchImpl||fetch);validatePlan(plan);const ordered=topologicalTasks(plan.tasks);if(ordered.length>MAX_AGENT_STEPS)throw new Error('Agent plan exceeds execution safety limit.');const permissions={...DEFAULT_PERMISSIONS,...(options.permissions||{})};const results={};const runId=options.runId||`agent_${Date.now()}_${Math.random().toString(36).slice(2,9)}`;startProgress(runId,cleanGoal,ordered);updateProgress(runId,{status:'executing',event:{type:'plan_ready',message:`Plan ready: ${ordered.length} steps.`}});try{for(const [index,task] of ordered.entries()){updateProgress(runId,{status:'executing',currentTask:{id:task.id,title:task.title,tool:task.tool,index:index+1},completedTasks:index,event:{type:'task_started',taskId:task.id,title:task.title,tool:task.tool}});try{results[task.id]=await executeTool(task.tool,task.input,results,{registry:TOOL_REGISTRY,permissions,runId,userId:options.userId,taskId:task.id,fetchImpl:options.fetchImpl||fetch});updateProgress(runId,{completedTasks:index+1,event:{type:'task_completed',taskId:task.id,title:task.title,tool:task.tool}});}catch(error){updateProgress(runId,{status:'failed',event:{type:'task_failed',taskId:task.id,title:task.title,tool:task.tool,error:error?.message||'Tool failed'}});throw error;}}finishProgress(runId,'completed',{completedTasks:ordered.length,event:{type:'run_completed',message:'All agent steps completed.'}});return{objective:plan.objective||cleanGoal,plan:ordered,results,status:'completed',runId,permissions};}catch(error){finishProgress(runId,'failed',{completedTasks:Object.keys(results).length,event:{type:'run_failed',message:error?.message||'Agent execution failed.'}});throw error;}}
export function registerAgentRoutes(app){registerAgentProgressRoutes(app);app.post('/api/agent',async(req,res)=>{try{const user=getPool()?await getSessionUser(req).catch(()=>null):null;const goal=String(req.body?.goal||'').trim();if(!goal)return res.status(400).json({error:'Agent goal is required.'});const result=await runAgent(goal,{userId:user?.id||null});if(getPool()&&user?.id){await query(`CREATE TABLE IF NOT EXISTS agent_runs (id TEXT PRIMARY KEY,user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,objective TEXT NOT NULL,plan JSONB NOT NULL,results JSONB NOT NULL,status TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await query('INSERT INTO agent_runs (id,user_id,objective,plan,results,status) VALUES($1,$2,$3,$4,$5,$6)',[result.runId,user.id,result.objective,JSON.stringify(result.plan),JSON.stringify(result.results),result.status])}res.json(result);}catch(e){console.error('Agent execution failed:',e?.message||e);res.status(400).json({error:e?.message||'Agent execution failed.'});}});}
export const _test={heuristicPlan,parseJson,validatePlan,topologicalTasks,TOOL_REGISTRY,TOOL_NAMES,MAX_GOAL_LENGTH,MAX_TASKS,MAX_AGENT_STEPS};