import { getPool, query } from './db.js';
import { getSessionUser } from './auth.js';
import { executeTool } from './tool-execution.js';

const API_BASE = 'https://generativelanguage.googleapis.com/v1beta/interactions';
const DEFAULT_MODEL = process.env.GEMINI_AGENT_MODEL || 'gemini-3.8-flash';
const MAX_GOAL_LENGTH = 12000;
const MAX_TASKS = 12;
const MAX_AGENT_STEPS = 16;

function apiKey() { return process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY || ''; }
function clampText(value, max) { return String(value || '').slice(0, max); }

const taskSchema = { type:'object', additionalProperties:false, properties:{ objective:{type:'string'}, tasks:{type:'array',minItems:1,maxItems:MAX_TASKS,items:{type:'object',additionalProperties:false,properties:{id:{type:'string'},title:{type:'string'},tool:{type:'string',enum:['research','verify','synthesize']},input:{type:'string'},depends_on:{type:'array',maxItems:MAX_TASKS,items:{type:'string'}},risk:{type:'string',enum:['low','medium','high']}},required:['id','title','tool','input','depends_on','risk']}}},required:['objective','tasks'] };

function heuristicPlan(goal) {
  const lower=goal.toLowerCase(); const tasks=[];
  if(/research|latest|compare|investigate|analy[sz]e|find|verify|sources|web/.test(lower)) {
    tasks.push({id:'research_1',title:'Research the objective',tool:'research',input:goal,depends_on:[],risk:'low'});
    tasks.push({id:'verify_1',title:'Verify important findings',tool:'verify',input:'Verify the factual findings from research_1.',depends_on:['research_1'],risk:'low'});
    tasks.push({id:'synthesize_1',title:'Synthesize a final answer',tool:'synthesize',input:goal,depends_on:['research_1','verify_1'],risk:'low'});
  } else tasks.push({id:'synthesize_1',title:'Analyze the user goal and produce an actionable answer',tool:'synthesize',input:goal,depends_on:[],risk:'low'});
  return {objective:goal,tasks};
}
function parseJson(text){const clean=String(text||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/i,'');try{return JSON.parse(clean)}catch{return null}}
async function planWithGemini(goal,fetchImpl=fetch){const key=apiKey();if(!key)return heuristicPlan(goal);const body={model:DEFAULT_MODEL,input:`You are the planner for an autonomous AI assistant. Decompose the user's goal into a small dependency-aware execution plan. Only use the tools research, verify, and synthesize. Never invent tools or claim an external action was performed. Prefer independent verification for factual research. Goal:\n${goal}`,store:false,response_format:{type:'text',mime_type:'application/json',schema:taskSchema}};const response=await fetchImpl(API_BASE,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message||`Agent planner failed (${response.status}).`);const parsed=parseJson(data?.output_text||(data?.steps||[]).flatMap(s=>s?.content||[]).map(x=>x?.text||'').join('\n'));if(!parsed||!Array.isArray(parsed.tasks)||!parsed.tasks.length)throw new Error('Agent planner returned an invalid plan.');parsed.tasks=parsed.tasks.slice(0,MAX_TASKS);return parsed}
function validatePlan(plan){if(!plan||!Array.isArray(plan.tasks)||plan.tasks.length<1||plan.tasks.length>MAX_TASKS)throw new Error('Invalid agent plan.');const ids=new Set();for(const task of plan.tasks){if(!task?.id||ids.has(task.id))throw new Error('Agent plan contains duplicate or missing task IDs.');if(!['research','verify','synthesize'].includes(task.tool))throw new Error('Agent plan contains an unsupported tool.');ids.add(task.id)}for(const task of plan.tasks)for(const dep of task.depends_on||[])if(!ids.has(dep))throw new Error(`Unknown task dependency: ${dep}`);return true}
function topologicalTasks(tasks){const pending=new Map(tasks.map(t=>[t.id,t]));const done=new Set();const ordered=[];while(pending.size){let progress=false;for(const[id,task]of pending)if((task.depends_on||[]).every(dep=>done.has(dep))){ordered.push(task);done.add(id);pending.delete(id);progress=true}if(!progress)throw new Error('Agent plan contains a dependency cycle.')}return ordered}
async function geminiTool(prompt,options={}){const key=apiKey();if(!key)return{status:'not_executed',reason:'Gemini API is not configured.'};const body={model:DEFAULT_MODEL,input:prompt,store:false};if(options.tools)body.tools=options.tools;const response=await(options.fetchImpl||fetch)(API_BASE,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.error?.message||`${options.name||'Agent tool'} failed (${response.status}).`);return{status:'completed',output:data?.output_text||(data?.steps||[]).flatMap(s=>s?.content||[]).map(x=>x?.text||'').filter(Boolean).join('\n'),steps:data?.steps||[]}}
async function runResearch(input,context,fetchImpl=fetch){return geminiTool(`Research this task and cite useful sources.\n\n${clampText(input,MAX_GOAL_LENGTH)}`,{tools:[{type:'google_search'}],fetchImpl,name:'Research tool'})}
async function runVerify(input,context,fetchImpl=fetch){return geminiTool(`Check the factual claims in this material. Identify supported, partially supported, contradicted, and unverified claims.\n\nTASK:\n${input}\n\nCONTEXT:\n${clampText(JSON.stringify(context),30000)}`,{tools:[{type:'google_search'}],fetchImpl,name:'Verification tool'})}
async function runSynthesize(input,context,fetchImpl=fetch){return geminiTool(`Produce a concise final answer for the user's goal. Use the execution evidence below, distinguish uncertainty, and never claim an action happened unless the evidence shows it.\n\nGOAL:\n${input}\n\nEXECUTION EVIDENCE:\n${clampText(JSON.stringify(context),45000)}`,{fetchImpl,name:'Synthesis tool'})}
const TOOL_REGISTRY={research:runResearch,verify:runVerify,synthesize:runSynthesize};

export async function runAgent(goal,options={}){const cleanGoal=String(goal||'').trim();if(!cleanGoal)throw new Error('Agent goal is required.');if(cleanGoal.length>MAX_GOAL_LENGTH)throw new Error('Agent goal is too long.');const plan=options.plan||await planWithGemini(cleanGoal,options.fetchImpl||fetch);validatePlan(plan);const ordered=topologicalTasks(plan.tasks);if(ordered.length>MAX_AGENT_STEPS)throw new Error('Agent plan exceeds execution safety limit.');const permissions=options.permissions||{web_read:true,file_read:true,code_execution:false,external_write:false,destructive_actions:false};const results={};const auditRunId=options.runId||`agent_${Date.now()}_${Math.random().toString(36).slice(2,9)}`;for(const task of ordered)results[task.id]=await executeTool(task.tool,task.input,results,{registry:TOOL_REGISTRY,permissions,runId:auditRunId,userId:options.userId,taskId:task.id,fetchImpl:options.fetchImpl||fetch});return{objective:plan.objective||cleanGoal,plan:ordered,results,status:'completed',runId:auditRunId,permissions}}

export function registerAgentRoutes(app){app.post('/api/agent',async(req,res)=>{try{const user=getPool()?await getSessionUser(req).catch(()=>null):null;const goal=String(req.body?.goal||'').trim();if(!goal)return res.status(400).json({error:'Agent goal is required.'});const result=await runAgent(goal,{userId:user?.id||null});if(getPool()&&user?.id){await query(`CREATE TABLE IF NOT EXISTS agent_runs (id TEXT PRIMARY KEY,user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,objective TEXT NOT NULL,plan JSONB NOT NULL,results JSONB NOT NULL,status TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await query('INSERT INTO agent_runs (id,user_id,objective,plan,results,status) VALUES($1,$2,$3,$4,$5,$6)',[result.runId,user.id,result.objective,JSON.stringify(result.plan),JSON.stringify(result.results),result.status])}res.json(result)}catch(error){console.error('Agent execution failed:',error?.message||error);res.status(400).json({error:error?.message||'Agent execution failed.'})}})}
export const _test={heuristicPlan,parseJson,validatePlan,topologicalTasks,TOOL_REGISTRY,MAX_GOAL_LENGTH,MAX_TASKS,MAX_AGENT_STEPS};
