import { getPool, query } from './db.js';
import { getSessionUser } from './auth.js';
import { riskForGoal, requiresApproval, permissionsForRisk } from './agent-governance.js';

const API_BASE = 'https://generativelanguage.googleapis.com/v1beta/interactions';
const DEFAULT_AGENT = process.env.GEMINI_MANAGED_AGENT || 'antigravity-preview-05-2026';
const MAX_GOAL_LENGTH = 12000;
const MAX_BACKGROUND_PER_IP_PER_HOUR = 3;
const ipWindows = new Map();
let tableReady = false;
function keyFor(req) { return req.ip || req.socket?.remoteAddress || 'unknown'; }
function apiKey() { return process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY || ''; }
function allowIp(key) { const now=Date.now(); const e=ipWindows.get(key); if(!e||now-e.start>=3600000){ipWindows.set(key,{start:now,count:1});return true;} if(e.count>=MAX_BACKGROUND_PER_IP_PER_HOUR)return false; e.count+=1; return true; }
async function ensureTable() { if(tableReady||!getPool())return; await query(`CREATE TABLE IF NOT EXISTS background_agent_runs (id TEXT PRIMARY KEY,user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,provider_job_id TEXT NOT NULL,goal TEXT NOT NULL,status TEXT NOT NULL,result JSONB NOT NULL DEFAULT '{}'::jsonb,error TEXT,permissions JSONB NOT NULL DEFAULT '{}'::jsonb,approval_id TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),completed_at TIMESTAMPTZ)`); tableReady=true; }
async function save(row) { if(!getPool())return; await ensureTable(); await query(`INSERT INTO background_agent_runs (id,user_id,provider_job_id,goal,status,result,error,permissions,approval_id,created_at,updated_at,completed_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,NOW(),NOW(),$10) ON CONFLICT(id) DO UPDATE SET status=EXCLUDED.status,result=EXCLUDED.result,error=EXCLUDED.error,permissions=EXCLUDED.permissions,approval_id=EXCLUDED.approval_id,updated_at=NOW(),completed_at=EXCLUDED.completed_at`,[row.id,row.userId||null,row.providerJobId,row.goal,row.status,JSON.stringify(row.result||{}),row.error||null,JSON.stringify(row.permissions||{}),row.approvalId||null,row.completedAt||null]); }
async function fetchInteraction(id) { const key=apiKey(); if(!key)throw new Error('Gemini background agent requires GEMINI_API_KEY or GOOGLE_API_KEY.'); const r=await fetch(`${API_BASE}/${encodeURIComponent(id)}`,{headers:{'x-goog-api-key':key,'Api-Revision':'2026-05-20'}}); const data=await r.json().catch(()=>({})); if(!r.ok)throw new Error(data?.error?.message||`Agent status failed (${r.status}).`); return data; }
function outputText(data) { if(typeof data?.output_text==='string')return data.output_text; return (data?.steps||[]).flatMap(s=>s?.content||[]).map(x=>x?.text||'').filter(Boolean).join('\n').trim(); }
export async function startBackgroundAgent(goal,userId=null,options={}) { const key=apiKey(); if(!key)throw new Error('Gemini background agent is not configured.'); const clean=String(goal||'').trim(); if(!clean)throw new Error('Agent goal is required.'); if(clean.length>MAX_GOAL_LENGTH)throw new Error('Agent goal is too long.'); const risk=riskForGoal(clean); if(requiresApproval(risk)&&!options.approvalId)throw new Error('Human approval is required before this agent can start.'); const permissions=options.permissions||permissionsForRisk(risk); const permissionText=`Approved tool policy: ${JSON.stringify(permissions)}. Never bypass these permissions. If a requested action is outside policy, stop and report that approval is required.`; const body={agent:DEFAULT_AGENT,input:`You are an autonomous execution agent. Complete the user's goal using only capabilities available to this managed agent. Work carefully, verify important results, and never claim an action succeeded unless you actually completed it.\n\n${permissionText}\n\nUSER GOAL:\n${clean}`,background:true,store:true,environment:'remote'}; const r=await fetch(API_BASE,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key,'Api-Revision':'2026-05-20'},body:JSON.stringify(body)}); const data=await r.json().catch(()=>({})); if(!r.ok)throw new Error(data?.error?.message||`Background agent failed to start (${r.status}).`); const id=`bagent_${Date.now()}_${Math.random().toString(36).slice(2,9)}`; await save({id,userId,providerJobId:data.id,goal:clean,status:data.status||'in_progress',permissions,approvalId:options.approvalId,result:{provider:DEFAULT_AGENT,providerJobId:data.id,risk,permissions}}); return {id,providerJobId:data.id,status:data.status||'in_progress',goal:clean,risk,permissions}; }
async function getOwnedRun(id,userId) { if(!getPool())return null; await ensureTable(); const r=await query('SELECT * FROM background_agent_runs WHERE id=$1',[id]); const row=r.rows[0]; if(!row||(row.user_id&&(!userId||Number(row.user_id)!==Number(userId))))return null; return row; }
async function unifiedTasks(userId,limit=50) { if(!getPool()||!userId)return []; await ensureTable(); const a=await query('SELECT id,goal,status,created_at,updated_at,completed_at FROM background_agent_runs WHERE user_id=$1 ORDER BY created_at DESC LIMIT $2',[userId,limit]); let r=[]; try { const q=await query('SELECT id,query AS goal,status,created_at,updated_at,completed_at FROM research_jobs WHERE user_id=$1 ORDER BY created_at DESC LIMIT $2',[userId,limit]); r=q.rows; } catch {} return [...a.rows.map(x=>({...x,type:'agent'})),...r.map(x=>({...x,type:'research'}))].sort((x,y)=>new Date(y.created_at)-new Date(x.created_at)).slice(0,limit).map(x=>({id:String(x.id),type:x.type,goal:x.goal,status:x.status,createdAt:x.created_at,updatedAt:x.updated_at,completedAt:x.completed_at||null})); }
export function registerBackgroundAgentRoutes(app) { app.post('/api/agent/background',async(req,res)=>{if(!allowIp(keyFor(req)))return res.status(429).json({error:'Background agent rate limit reached. Try again later.'}); const user=getPool()?await getSessionUser(req).catch(()=>null):null; try{res.status(202).json(await startBackgroundAgent(req.body?.goal,user?.id||null));}catch(error){const code=/approval is required/i.test(error?.message||'')?409:400;res.status(code).json({error:error?.message||'Background agent failed to start.'});}});
app.get('/api/agent/background',async(req,res)=>{const user=getPool()?await getSessionUser(req).catch(()=>null):null;if(!user?.id)return res.json({tasks:[]});try{const tasks=(await unifiedTasks(user.id,50)).filter(x=>x.type==='agent');res.json({tasks});}catch(error){res.status(500).json({error:'Could not load agent task history.'});}});
app.get('/api/tasks',async(req,res)=>{const user=getPool()?await getSessionUser(req).catch(()=>null):null;if(!user?.id)return res.status(401).json({error:'Login required to view task history.'});try{res.json({tasks:await unifiedTasks(user.id,50)});}catch(error){res.status(500).json({error:'Could not load unified task history.'});}});
app.get('/api/agent/background/:id',async(req,res)=>{const user=getPool()?await getSessionUser(req).catch(()=>null):null; try{const row=await getOwnedRun(req.params.id,user?.id||null);if(!row)return res.status(404).json({error:'Background agent run not found.'});const data=await fetchInteraction(row.provider_job_id);const terminal=['completed','failed','cancelled','incomplete','budget_exceeded'].includes(data.status);const result={id:row.id,providerJobId:row.provider_job_id,goal:row.goal,status:data.status,output:outputText(data),steps:data.steps||[],error:data.error||null,permissions:row.permissions||{}};if(terminal)await save({id:row.id,userId:row.user_id,providerJobId:row.provider_job_id,goal:row.goal,status:data.status,result,permissions:row.permissions,approvalId:row.approval_id,error:data.error?.message||null,completedAt:new Date().toISOString()});else await save({id:row.id,userId:row.user_id,providerJobId:row.provider_job_id,goal:row.goal,status:data.status,result,permissions:row.permissions,approvalId:row.approval_id});res.json(result);}catch(error){res.status(400).json({error:error?.message||'Background agent status failed.'});}});
app.post('/api/agent/background/:id/cancel',async(req,res)=>{const user=getPool()?await getSessionUser(req).catch(()=>null):null;try{const row=await getOwnedRun(req.params.id,user?.id||null);if(!row)return res.status(404).json({error:'Background agent run not found.'});const key=apiKey();const r=await fetch(`${API_BASE}/${encodeURIComponent(row.provider_job_id)}/cancel`,{method:'POST',headers:{'x-goog-api-key':key,'Api-Revision':'2026-05-20'}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.error?.message||`Agent cancellation failed (${r.status}).`);const result={id:row.id,providerJobId:row.provider_job_id,status:data.status||'cancelled'};await save({id:row.id,userId:row.user_id,providerJobId:row.provider_job_id,goal:row.goal,status:result.status,result,permissions:row.permissions,approvalId:row.approval_id,completedAt:new Date().toISOString()});res.json(result);}catch(error){res.status(400).json({error:error?.message||'Background agent cancellation failed.'});}}); }
export const _test={allowIp,outputText,MAX_GOAL_LENGTH,MAX_BACKGROUND_PER_IP_PER_HOUR,DEFAULT_AGENT,riskForGoal,requiresApproval,permissionsForRisk,unifiedTasks};
